In [1]:
import pyquasar as pq
import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv

np.set_printoptions(precision=3, suppress=True)
%config InlineBackend.figure_format='retina'
%load_ext line_profiler

In [2]:
plt.rcParams.update(
  {
    "figure.figsize": (6, 6),
    "axes.facecolor": "none",
    "font.size": 10,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
  }
)

In [3]:
# mesh = pq.Mesh.load("tetra.geo", refine_k=1)
mesh = pq.Mesh.load("cube.geo", refine_k=0)
mesh

<Mesh object summary 
	Numeration: global
	Domains: [<MeshDomain object summary
	Material: steel
	Total elements number: 17
	Element type: Tetrahedron 4; Count: 17
	Boundary type: dirichlet; Tag: 1; Element type: Triangle 3; Count: 4.
	Boundary type: neumann; Tag: 2; Element type: Triangle 3; Count: 2.
	Boundary type: dirichlet; Tag: 3; Element type: Triangle 3; Count: 4.
	Boundary type: None; Tag: 4; Element type: Triangle 3; Count: 8.
	Boundary type: neumann; Tag: 8; Element type: Triangle 3; Count: 2.
>, <MeshDomain object summary
	Material: air
	Total elements number: 17
	Element type: Tetrahedron 4; Count: 17
	Boundary type: None; Tag: 4; Element type: Triangle 3; Count: 8.
	Boundary type: dirichlet; Tag: 5; Element type: Triangle 3; Count: 4.
	Boundary type: dirichlet; Tag: 6; Element type: Triangle 3; Count: 4.
	Boundary type: neumann; Tag: 7; Element type: Triangle 3; Count: 2.
	Boundary type: neumann; Tag: 9; Element type: Triangle 3; Count: 2.
>]>

In [16]:
def u(p, n):
  # return p[..., 0] ** 2 - p[..., 1] ** 2
  return 2 * p[..., 0] + 2 * p[..., 1] + 2 * p[..., 2]
  return 2 * p[..., 0] + 3 * p[..., 1] + 5 * p[..., 2] - 4


def flow(p, n):
  # return 2 * p[..., 0] * n[..., 0] - 2 * p[..., 1] * n[..., 1]
  return 2 * n[..., 0] + 2 * n[..., 1] + 2 * n[..., 2]
  return 2 * n[..., 0] + 3 * n[..., 1] + 5 * n[..., 2]

In [17]:
materials = {
  "dirichlet": u,
  "steel": {"neumann": flow, "steel": 0},
  "air": {"neumann": flow, "air": 0},
}

domains = [pq.FemDomain(domain) for domain in mesh.domains]
problem = pq.FemProblem(domains)
problem.assembly(materials)
problem.add_skeleton_projection(u, ["dirichlet"])
sol = problem.solve()
rel_err = np.linalg.norm(sol - u(mesh.domains[0].vertices, 0)) / np.linalg.norm(u(mesh.domains[0].vertices, 0))
print(f"Relative error: {rel_err:.2e}")

Relative error: 2.86e-16


In [18]:
# points = mesh.domains[0].vertices
# cells = np.array([np.insert(element, 0, 4) for element in mesh.domains[0].elements[0].node_tags])
# # cells1 = np.array([np.insert(element, 0, 4) for element in mesh.domains[0].elements[0].node_tags])
# # cells2 = np.array([np.insert(element, 0, 4) for element in mesh.domains[1].elements[0].node_tags])
# # cells = np.concatenate([cells1, cells2])
# celltypes = [pv.CellType.TETRA] * cells.shape[0]

# pv.set_jupyter_backend("trame")
# # pv.set_jupyter_backend("static")

# grid = pv.UnstructuredGrid()
# grid = pv.UnstructuredGrid(cells, celltypes, points)
# grid.point_data["u"] = sol
# grid.plot(show_edges=True)

In [40]:
points = np.array(
  [
    [0, 0, 0],
    [0.1, 0.1, 0.1],
    [0.5, 0, 0],
    [0.5, 0, 0.5],
    [0, 1.0, 0],
  ]
)
proj = problem.project_into(points)

In [41]:
np.linalg.norm(proj @ sol - u(points, 0)) / np.linalg.norm(u(points, 0))

1.4187544826906154e-16

In [42]:
proj_grad = problem.project_grad_into(points)
proj_grad[0] @ sol, proj_grad[1] @ sol, proj_grad[2] @ sol

(array([2., 2., 2., 2., 4.]),
 array([2., 2., 2., 2., 4.]),
 array([2., 2., 2., 2., 4.]))

In [43]:
proj_grad[0].sum(axis=1)

array([0., 0., 0., 0., 0.])

In [44]:
grad_x = np.array([2 for p in points])
grad_y = np.array([2 for p in points])
grad_z = 2 * np.ones(points.shape[0])
(
  np.linalg.norm(grad_x - proj_grad[0] @ sol) / np.linalg.norm(grad_x),
  np.linalg.norm(grad_y - proj_grad[1] @ sol) / np.linalg.norm(grad_y),
  np.linalg.norm(grad_z - proj_grad[2] @ sol) / np.linalg.norm(grad_z),
)

(0.4472135954999581, 0.44721359549995693, 0.4472135954999583)